# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 041c6435687edee75fc99d7c417c0aeeb6901bf140a88315c6673595758d04bd3a38a6bb7188241b0e67629378881c31505839a1e9330456b4451683212e2810

test:
  secret_key_base: 2350ec1fb253845363552a0f188232eb8838c6ba445560b2c63452405bf14cd07401f91e8199dadcac154025d2cc6a318ae601968ba5d37214702b38d1d0c56f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
